{% set name = "PyFstat" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d0e8e6daa3e9360907cece149ec4dcca006b52977abb95df27b2a86b8a8c73a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }},<=3.12
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<=3.12
    - numpy <2.0
    - matplotlib-base >=3.3
    - scipy
    - ptemcee
    - corner
    - dill
    - tqdm
    - pathos
    - python-lal >=7.1.5
    - python-lalpulsar >=6.0
    - lalpulsar >=6.0
    - attrs

test:
  requires:
    - pytest<8.2.2
    - flaky
    - python {{ python_min }}
  imports:
    - pyfstat
  source_files:
    - tests/*.py
  commands:
    - python -m pytest tests/

about:
  home: https://github.com/PyFstat/PyFstat/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a python package for gravitational wave analysis with the F-statistic
  description: |
    This is a python package providing an interface to perform F-statistic based continuous gravitational wave (CW) searches.
  dev_url: https://github.com/PyFstat/PyFstat/

extra:
  recipe-maintainers:
    - dbkeitel
