{% set name = "PyFstat" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12ba4cc75bad329947bd3757085dd79378922418465aa3c66f69a663b535846f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base >=2.1
    - scipy
    - ptemcee
    - corner
    - dill
    - tqdm
    - bashplotlib
    - peakutils
    - pathos
    - python-lal >=7.1.5
    - python-lalpulsar >=3.1.1
    - lalapps >=7.4.0

test:
  requires:
    - pytest
  imports:
    - pyfstat
  source_files:
    - tests.py
  commands:
    - python -m pytest tests.py

about:
  home: https://github.com/PyFstat/PyFstat/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a python package for gravitational wave analysis with the F-statistic
  description: |
    This is a python package providing an interface to perform F-statistic based continuous gravitational wave (CW) searches.
  dev_url: https://github.com/PyFstat/PyFstat/

extra:
  recipe-maintainers:
    - dbkeitel
