{% set name = "PyFstat" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d6aa0f9cc17606f907b5e4a39165e99828d608c0bccbbf2b102b7c1d6a47c2cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - attrs
    - corner
    - dill
    - lalpulsar >=6.0
    - matplotlib-base >=3.3
    - numpy <2.0
    - pandas
    - pathos
    - ptemcee
    - python >={{ python_min }},<3.13a0
    - python-lal >=7.1.5
    - python-lalpulsar >=6.0
    - scipy
    - tqdm

test:
  requires:
    - pytest<8.2.2
    - flaky
    - python {{ python_min }}
  imports:
    - pyfstat
  source_files:
    - tests/*.py
  commands:
    - python -m pytest tests/

about:
  home: https://github.com/PyFstat/PyFstat/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a python package for gravitational wave analysis with the F-statistic
  description: |
    This is a python package providing an interface to perform F-statistic based continuous gravitational wave (CW) searches.
  dev_url: https://github.com/PyFstat/PyFstat/

extra:
  recipe-maintainers:
    - dbkeitel
