{% set name = "PyFstat" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a9069c837664e9ec3d81ab3edebaf3d3e9cd96f2fcf5984dbd720f2f052e52e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base >=2.1
    - scipy
    - ptemcee
    - corner
    - dill
    - tqdm
    - pathos
    - python-lal >=7.1.5
    - python-lalpulsar >=5.0.0,<6.0.0
    - lalpulsar >=5.0.0,<6.0.0
    - attrs

test:
  requires:
    - pytest
    - flaky
  imports:
    - pyfstat
  source_files:
    - tests/*.py
  commands:
    - python -m pytest tests/

about:
  home: https://github.com/PyFstat/PyFstat/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a python package for gravitational wave analysis with the F-statistic
  description: |
    This is a python package providing an interface to perform F-statistic based continuous gravitational wave (CW) searches.
  dev_url: https://github.com/PyFstat/PyFstat/

extra:
  recipe-maintainers:
    - dbkeitel
